version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: jcrechriou
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Port pour la base

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  apiweb:
    build:
      context: .
      dockerfile: apiweb/Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
      - "5005:5005" # Port pour le débogage à distance
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/source_db
      SPRING_DATASOURCE_USERNAME: jcrechriou
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
